import { PageContent } from "../content-handler";

export const yarnLockContent: PageContent = {
  content: `
# THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
# yarn lockfile v1


I really did not want to see what happens if I paste 3000 lines of gibberish here...
`
}